### PR TITLE
several improvements and bugfixes

### PR DESCRIPTION
**Pull request by starius**
Changes:
- function `check()` checks heap's integrity
- fix bug: remove in unique heap breaks integrity of payloads
- do not create field payload in plain heaps
- add Dijkstra's algorithm as test

### CODE REVIEW

**Comment by Tieske** [comment]
`check` is a test function, not a production function.

if we remove payload, then we need yet another one, plain with payloads....

**Comment by starius** [comment]
> check is a test function, not a production function.

Agree

**Comment by Tieske** [comment]
@starius just gave you push access to the repo, as I won't be able to spend any time on it myself shortly...

**Comment by starius** [comment]
thank you!

**Pull request merged**
